version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "mySQLServer!"
      MSSQL_PID: "Express"
    ports: 
      - 1433:1433
  